name: Stupendous
favicon: null
layout_spectrum: 0.8336326549760997
typography_spectrum: 0.9412335599772632
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.20294315041974187
  lightness: 0.6196770046371967
  saturation: 0.3720678314566612
  rhythmicContrast: 0.7347719280514866
purpose: []
